// Control-plane API for seine.
//
// The management server is a stateful registry of agent runtime data:
// public keys, currently-advertised endpoints, last-seen timestamps. The
// network specification (groups, ACLs, hub mesh) lives in Git, not here;
// agents and the server pull it independently. This API exists only to
// exchange runtime data that cannot be expressed declaratively.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: seine/controlplane/v1/controlplane.proto

package cpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_HUB         Role = 1
	Role_ROLE_SPOKE       Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_HUB",
		2: "ROLE_SPOKE",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_HUB":         1,
		"ROLE_SPOKE":       2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_seine_controlplane_v1_controlplane_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_seine_controlplane_v1_controlplane_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_seine_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name as declared in the network spec (must match exactly).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Operator-issued bootstrap token. The server compares it against its
	// own configured value.
	BootstrapToken string `protobuf:"bytes,2,opt,name=bootstrap_token,json=bootstrapToken,proto3" json:"bootstrap_token,omitempty"`
	// WireGuard public key (base64, 32 bytes decoded).
	PublicKey string `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Endpoint the peer listens on, in host:port form. Hubs always set
	// this; spokes typically leave it empty (they connect outbound only).
	Endpoint string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Build version of the agent — surfaced in diagnostics.
	AgentVersion  string `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_seine_controlplane_v1_controlplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seine_controlplane_v1_controlplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_seine_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetBootstrapToken() string {
	if x != nil {
		return x.BootstrapToken
	}
	return ""
}

func (x *RegisterRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bearer token to present in subsequent calls.
	AuthToken     string `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_seine_controlplane_v1_controlplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seine_controlplane_v1_controlplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_seine_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current advertised endpoint. Empty means "unchanged" — the server
	// keeps the previously-registered value.
	Endpoint      string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_seine_controlplane_v1_controlplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seine_controlplane_v1_controlplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_seine_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Latest commit SHA of the spec the server has observed. The agent
	// uses this as a hint to prioritise its next Git pull.
	SpecCommit string `protobuf:"bytes,1,opt,name=spec_commit,json=specCommit,proto3" json:"spec_commit,omitempty"`
	// All currently-registered peers, including the caller. The agent
	// filters this list locally based on the spec and its role.
	Peers         []*PeerInfo `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_seine_controlplane_v1_controlplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seine_controlplane_v1_controlplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_seine_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSpecCommit() string {
	if x != nil {
		return x.SpecCommit
	}
	return ""
}

func (x *HeartbeatResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type PeerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name as declared in the spec.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// WireGuard public key (base64).
	PublicKey string `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Currently advertised endpoint (host:port). May be empty for spokes.
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Tunnel IP from the spec, included as a convenience so the agent
	// does not have to cross-reference itself.
	TunnelIp string `protobuf:"bytes,4,opt,name=tunnel_ip,json=tunnelIp,proto3" json:"tunnel_ip,omitempty"`
	// Last successful heartbeat, used by the agent to skip stale peers.
	LastSeen *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// Role of this peer (hub or spoke), copied from the spec.
	Role          Role `protobuf:"varint,6,opt,name=role,proto3,enum=seine.controlplane.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_seine_controlplane_v1_controlplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_seine_controlplane_v1_controlplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_seine_controlplane_v1_controlplane_proto_rawDescGZIP(), []int{4}
}

func (x *PeerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PeerInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PeerInfo) GetTunnelIp() string {
	if x != nil {
		return x.TunnelIp
	}
	return ""
}

func (x *PeerInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *PeerInfo) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

var File_seine_controlplane_v1_controlplane_proto protoreflect.FileDescriptor

const file_seine_controlplane_v1_controlplane_proto_rawDesc = "" +
	"\n" +
	"(seine/controlplane/v1/controlplane.proto\x12\x15seine.controlplane.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x01\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0fbootstrap_token\x18\x02 \x01(\tR\x0ebootstrapToken\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\"1\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\".\n" +
	"\x10HeartbeatRequest\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\"k\n" +
	"\x11HeartbeatResponse\x12\x1f\n" +
	"\vspec_commit\x18\x01 \x01(\tR\n" +
	"specCommit\x125\n" +
	"\x05peers\x18\x02 \x03(\v2\x1f.seine.controlplane.v1.PeerInfoR\x05peers\"\xe0\x01\n" +
	"\bPeerInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x1b\n" +
	"\ttunnel_ip\x18\x04 \x01(\tR\btunnelIp\x127\n" +
	"\tlast_seen\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12/\n" +
	"\x04role\x18\x06 \x01(\x0e2\x1b.seine.controlplane.v1.RoleR\x04role*:\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bROLE_HUB\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_SPOKE\x10\x022\xcb\x01\n" +
	"\fControlPlane\x12[\n" +
	"\bRegister\x12&.seine.controlplane.v1.RegisterRequest\x1a'.seine.controlplane.v1.RegisterResponse\x12^\n" +
	"\tHeartbeat\x12'.seine.controlplane.v1.HeartbeatRequest\x1a(.seine.controlplane.v1.HeartbeatResponseBCZAgithub.com/ilyapiatykh/seine/api/proto/seine/controlplane/v1;cpv1b\x06proto3"

var (
	file_seine_controlplane_v1_controlplane_proto_rawDescOnce sync.Once
	file_seine_controlplane_v1_controlplane_proto_rawDescData []byte
)

func file_seine_controlplane_v1_controlplane_proto_rawDescGZIP() []byte {
	file_seine_controlplane_v1_controlplane_proto_rawDescOnce.Do(func() {
		file_seine_controlplane_v1_controlplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seine_controlplane_v1_controlplane_proto_rawDesc), len(file_seine_controlplane_v1_controlplane_proto_rawDesc)))
	})
	return file_seine_controlplane_v1_controlplane_proto_rawDescData
}

var file_seine_controlplane_v1_controlplane_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_seine_controlplane_v1_controlplane_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_seine_controlplane_v1_controlplane_proto_goTypes = []any{
	(Role)(0),                     // 0: seine.controlplane.v1.Role
	(*RegisterRequest)(nil),       // 1: seine.controlplane.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 2: seine.controlplane.v1.RegisterResponse
	(*HeartbeatRequest)(nil),      // 3: seine.controlplane.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 4: seine.controlplane.v1.HeartbeatResponse
	(*PeerInfo)(nil),              // 5: seine.controlplane.v1.PeerInfo
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_seine_controlplane_v1_controlplane_proto_depIdxs = []int32{
	5, // 0: seine.controlplane.v1.HeartbeatResponse.peers:type_name -> seine.controlplane.v1.PeerInfo
	6, // 1: seine.controlplane.v1.PeerInfo.last_seen:type_name -> google.protobuf.Timestamp
	0, // 2: seine.controlplane.v1.PeerInfo.role:type_name -> seine.controlplane.v1.Role
	1, // 3: seine.controlplane.v1.ControlPlane.Register:input_type -> seine.controlplane.v1.RegisterRequest
	3, // 4: seine.controlplane.v1.ControlPlane.Heartbeat:input_type -> seine.controlplane.v1.HeartbeatRequest
	2, // 5: seine.controlplane.v1.ControlPlane.Register:output_type -> seine.controlplane.v1.RegisterResponse
	4, // 6: seine.controlplane.v1.ControlPlane.Heartbeat:output_type -> seine.controlplane.v1.HeartbeatResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_seine_controlplane_v1_controlplane_proto_init() }
func file_seine_controlplane_v1_controlplane_proto_init() {
	if File_seine_controlplane_v1_controlplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seine_controlplane_v1_controlplane_proto_rawDesc), len(file_seine_controlplane_v1_controlplane_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seine_controlplane_v1_controlplane_proto_goTypes,
		DependencyIndexes: file_seine_controlplane_v1_controlplane_proto_depIdxs,
		EnumInfos:         file_seine_controlplane_v1_controlplane_proto_enumTypes,
		MessageInfos:      file_seine_controlplane_v1_controlplane_proto_msgTypes,
	}.Build()
	File_seine_controlplane_v1_controlplane_proto = out.File
	file_seine_controlplane_v1_controlplane_proto_goTypes = nil
	file_seine_controlplane_v1_controlplane_proto_depIdxs = nil
}
